/*
 * generated by Xtext
 */
package com.shs.hl.tools.codevalidator;

import org.eclipse.xtext.junit4.GlobalRegistries;
import org.eclipse.xtext.junit4.GlobalRegistries.GlobalStateMemento;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.eclipse.xtext.junit4.IRegistryConfigurator;

import com.google.inject.Injector;
import com.shs.hl.HearingLanguageStandaloneSetup;

public class HearingLanguageInjectorProvider implements IInjectorProvider,
		IRegistryConfigurator {
	protected GlobalStateMemento	globalStateMemento;
	protected Injector				injector;

	static {
		GlobalRegistries.initializeDefaults();
	}

	@Override
	public Injector getInjector() {
		if (injector == null) {
			this.injector = new HearingLanguageStandaloneSetup()
					.createInjectorAndDoEMFRegistration();
		}
		return injector;
	}

	@Override
	public void restoreRegistry() {
		globalStateMemento.restoreGlobalState();
	}

	@Override
	public void setupRegistry() {
		globalStateMemento = GlobalRegistries.makeCopyOfGlobalState();
		if (injector != null)
			new HearingLanguageStandaloneSetup().register(injector);
	}

}
