/*
 * generated by Xtext
 */
package com.shs.hl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.autoedit.DefaultAutoEditStrategyProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.DefaultHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import com.shs.hl.ui.contentassist.AutoEditingStrategyProvider;
import com.shs.hl.ui.highlighting.HLHighlightingConfiguration;
import com.shs.hl.ui.highlighting.HLSemanticHighlightingCalculator;
import com.shs.hl.ui.hover.HLHover;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HearingLanguageUiModule extends
		com.shs.hl.ui.AbstractHearingLanguageUiModule {
	public HearingLanguageUiModule(final AbstractUIPlugin plugin) {
		super(plugin);
	}

	@Override
	public Class<? extends org.eclipse.jface.text.ITextHover> bindITextHover() {
		return HLHover.class;
	}

	public Class<? extends DefaultHighlightingConfiguration> bindHighlightingConfiguration() {
		return HLHighlightingConfiguration.class;
	}

	public Class<? extends DefaultAutoEditStrategyProvider> bindAutoEditingStrategyProvider() {
		return AutoEditingStrategyProvider.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
		return HLSemanticHighlightingCalculator.class;
	}

	@Override
	public Class<? extends org.eclipse.xtext.builder.IXtextBuilderParticipant> bindIXtextBuilderParticipant() {
		// return
		// org.eclipse.xtext.builder.JavaProjectBasedBuilderParticipant.class;
		return org.eclipse.xtext.builder.BuilderParticipant.class;
	}

	@Override
	public org.eclipse.core.resources.IWorkspaceRoot bindIWorkspaceRootToInstance() {
		return org.eclipse.core.resources.ResourcesPlugin.getWorkspace().getRoot();
	}

//	// contributed by org.eclipse.xtext.ui.generator.projectWizard.SimpleProjectWizardFragment
//	public Class<? extends org.eclipse.xtext.ui.wizard.IProjectCreator> bindIProjectCreator() {
////		return com.shs.hl.ui.wizard.HearingLanguageProjectCreator.class;
//		return com.shs.hl.ui.wizard.JDTFreeHearingLanguageProjectCreator.class;
//	}

//	/**
//	 * @see org.eclipse.xtext.ui.DefaultUiModule#bindIResourceForEditorInputFactory()
//	 */
//	@Override
//	public Class<? extends IResourceForEditorInputFactory> bindIResourceForEditorInputFactory() {
//		return ResourceForIEditorInputFactory.class;
//	}

//	/**
//	 * @see org.eclipse.xtext.ui.DefaultUiModule#bindIResourceSetProvider()
//	 */
//	@Override
//	public Class<? extends IResourceSetProvider> bindIResourceSetProvider() {
//		return SimpleResourceSetProvider.class;
//	}
//
//
//	// contributed by org.eclipse.xtext.ui.generator.ImplicitUiFragment
//	public com.google.inject.Provider<org.eclipse.xtext.resource.containers.IAllContainersState> provideIAllContainersState() {
//		return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
//	}

}
