/*
 * generated by Xtext
 */
package com.shs.hl.ui.outline;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

import com.shs.hl.hearingLanguage.FunctionDeclaration;

/**
 * customization of the default outline structure
 * 
 */
public class HearingLanguageOutlineTreeProvider extends
		DefaultOutlineTreeProvider {

	@Override
	protected boolean _isLeaf(final EObject modelElement) {
		if (modelElement instanceof FunctionDeclaration) return true;
		return super._isLeaf(modelElement);
	}

}
