/*
 * generated by Xtext
 */
package com.shs.hl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HearingLanguageTestUiModule extends com.shs.hl.ui.AbstractHearingLanguageTestUiModule {
	public HearingLanguageTestUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
