/*
* generated by Xtext
*/
package com.shs.common.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CommonLanguageProposalProvider extends AbstractCommonLanguageProposalProvider {

}
