/*
 * generated by Xtext
 */
package com.shs.hl.scoping;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
public class HearingLanguageTestScopeProvider extends com.shs.common.scoping.CommonLanguageScopeProvider {

}
