/*
 * generated by Xtext
 */
package com.shs.common.scoping;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

import com.shs.common.commonLanguage.EnumParameter;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#scoping
 * on how and when to use it 
 *
 */
public class CommonLanguageScopeProvider extends AbstractDeclarativeScopeProvider {

	public IScope scope_EnumParameter_undefElement( EnumParameter ctx, EReference ref ) {
		return Scopes.scopeFor(ctx.getLiterals());
	}
	
	
}
