/*
 * generated by Xtext
 */
package com.shs.common;

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;

import com.shs.common.od.CommonResourceDescriptionStrategy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CommonLanguageRuntimeModule extends com.shs.common.AbstractCommonLanguageRuntimeModule {

	public Class<? extends IDefaultResourceDescriptionStrategy> bindIDefaultResourceDescriptionStrategy() {
		return CommonResourceDescriptionStrategy.class;
	}
	
}  
