/*
* generated by Xtext
*/
package com.shs.common.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class CommonLanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
	
	
}
