/*
* generated by Xtext
*/
package com.shs.hl.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class HearingLanguageTestProposalProvider extends com.shs.hl.ui.contentassist.AbstractHearingLanguageTestProposalProvider {

}
