/*
 * generated by Xtext
 */
package com.shs.hl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HearingLanguageTestRuntimeModule extends com.shs.hl.AbstractHearingLanguageTestRuntimeModule {

}
