/*
* generated by Xtext
*/
package com.shs.hl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class HearingLanguageTestStandaloneSetup extends HearingLanguageTestStandaloneSetupGenerated{

	public static void doSetup() {
		new HearingLanguageTestStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

